### ISSUE TITLE
alternatives for Hydrated Lime

### ISSUE THREAD

**Issue by DanTaranis** [openair-collective/openair-cyan#5]

**Comment by DanTaranis** [comment]
Hi - I want to do a DIY session with the people in my company - we are in Israel - and apparently Hydrated Lime is super rare here because the ground is already somewhat basic. 

Are there any simple cheap alternatives?

**Comment by DanTaranis** [comment]
after some research it looks like an alternative is magnesium oxide pills (crushed) - if I understand correctly - magnesium oxide turns into magnesium hydroxide when in water. 
its super expensive per kilo but we don't need much for the experiment

**Comment by DanTaranis** [comment]
from seeing your youtube videos it sounds like I can also just buy cement - mix it with water and then break it up and use that?

**Comment by dahlwinters** [comment]
Hi @DanTaranis, great to meet you! While calcium (or magnesium) oxide does take up CO2 to form calcium carbonate, it is produced by calcining limestone which gives off a large amount of CO2. Calcium hydroxide (hydrated lime, which is hydrated calcium oxide) at least has the option of being made without calcination (presently in small amounts). If there are saltwater aquaria nearby, they will carry a very pure calcium hydroxide as kalkwasser.

Magnesium hydroxide powder is available online - I wouldn't get pills since they contain binders and other ingredients that might also react with CO2 or the water used.

If you add water to cement, it will definitely harden and form calcium hydroxide but the amount of calcium hydroxide you'll obtain is relatively small (20-25%) - the rest is mostly a calcium-silicate-hydrate gel. Crushing recycled concrete aggregate and carbonating it in the presence of humidity would help to carbonate that small fraction of calcium hydroxide and that would indeed take up CO2, but you will likely get other minerals forming, making it impossible to determine the carbon captured using the weight difference.

**Comment by danFromTelAviv** [comment]
thank you for your super thorough answer. 
as this is mostly for educational reasons 20-25% is good enough for me but ill make sure to let everyone know that in reality this exact material is not "it". 

thanks!

**Comment by ZanzyTHEbar** [comment]
Closing issue, and added tags for future people to be able to view this topic :)
